package com.model;

public enum ALARM_TYPE {
    COMMUNITY_KAKAO_ALARM,
    COMMUNITY_EMAIL_ALARM,
    COMMENT_KAKAO_ALARM,
    COMMENT_EMAIL_ALARM,
    SERVICE_KAKAO_ALARM,
    SERVICE_EMAIL_ALARM,
}
